// Web_Frame/Vue/代码/vue_test/36_src_router-link的replace属性/pages/Home.vue
<template>
  <div>
    <h2>Home组件内容</h2>
    <div>
      <ul class="nav nav-tabs">
        <li>
          <!-- 变为replace模式，点击跳转后浏览器无法后退 -->
          <router-link replace class="list-group-item" active-class="active" to="/home/news">News</router-link>
        </li>
        <li>
          <!-- 变为replace模式，点击跳转后浏览器无法后退 -->
          <router-link
            replace
            class="list-group-item"
            active-class="active"
            to="/home/message"
          >Message</router-link>
        </li>
      </ul>
      <router-view></router-view>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Home'
  /* beforeDestroy() {
			console.log('Home组件即将被销毁了')
		}, */
  /* mounted() {
			console.log('Home组件挂载完毕了',this)
			window.homeRoute = this.$route
			window.homeRouter = this.$router
		},  */
}
</script>

// Web_Frame/React/代码/react-router6_test/13_src_useOutlet/pages/Home.jsx
import React from 'react'
import { NavLink, Outlet, useOutlet } from 'react-router-dom'

export default function Home() {
  console.log('###', useOutlet())
  return (
    <div>
      <h2>Home组件内容</h2>
      <div>
        <ul className="nav nav-tabs">
          <li>
            <NavLink className="list-group-item" replace to="news">
              News
            </NavLink>
          </li>
          <li>
            <NavLink className="list-group-item" to="message">
              Message
            </NavLink>
          </li>
        </ul>
        {/* 指定路由组件呈现的位置 */}
        <Outlet />
      </div>
    </div>
  )
}
