// Web_Frame/Vue/代码/vue_test/src/pages/Detail.vue
<template>
  <ul>
    <li>消息编号：{{id}}</li>
    <li>消息标题：{{title}}</li>
    <li>a:{{a}}</li>
    <li>b:{{b}}</li>
  </ul>
</template>

<script>
export default {
  name: 'Detail',
  props: ['id', 'title', 'a', 'b'],
  computed: {
    // id(){
    // 	return this.$route.query.id
    // },
    // title(){
    // 	return this.$route.query.title
    // },
  },
  mounted() {
    // console.log(this.$route)
  }
}
</script>

// Web_Frame/React/代码/react-router6_test/07_src_路由的search参数/pages/Detail.jsx
import React from 'react'
import { useSearchParams, useLocation } from 'react-router-dom'

export default function Detail() {
  const [search, setSearch] = useSearchParams()
  const id = search.get('id')
  const title = search.get('title')
  const content = search.get('content')
  const x = useLocation()
  console.log('@', x)
  return (
    <ul>
      <li>
        <button onClick={() => setSearch('id=008&title=哈哈&content=嘻嘻')}>点我更新一下收到的search参数</button>
      </li>
      <li>消息编号：{id}</li>
      <li>消息标题：{title}</li>
      <li>消息内容：{content}</li>
    </ul>
  )
}
